# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "50e88c83585f31fce174a34d763c4441"
application_url = "https://walk-humans-representations-switch.trycloudflare.com"
embedded = true
name = "ms-pmax"
handle = "ms-pmax"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://walk-humans-representations-switch.trycloudflare.com/auth/callback",
  "https://walk-humans-representations-switch.trycloudflare.com/auth/shopify/callback",
  "https://walk-humans-representations-switch.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
